apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.0.4
  selector:
    app: phpmyadmin
  ports:
  - port: 5000
    targetPort: 80
    protocol: TCP
    name: php-port

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: my_phpmyadmin
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: php-port