apiVersion: 1
datasources:
    - name: InfluxDB_Container_Services
      type: influxdb
      access: proxy
      url: http://influxdb-service:8086
      database: telegraf
      user: user
      password: password